export const APP_CONFIG = {
  PORT: 3000,
  POLL_INTERVAL_ICMP: 30, // seconds
  POLL_INTERVAL_SNMP: 60,
  POLL_INTERVAL_ROUTEROS: 30,
  POLL_INTERVAL_SSH: 120,
  
  FAILURE_THRESHOLD: 3, // consecutive failures before DOWN
  
  ANOMALY_THRESHOLDS: {
    LATENCY_MULTIPLIER: 3,     // current > (avg * 3)
    PACKET_LOSS_PCT: 5,        // > 5% loss
    CPU_PCT: 90,               // > 90% for 3 consecutive polls
    TRAFFIC_MULTIPLIER: 5,     // > 5x baseline
  },
  
  MAX_HISTORY_PER_DEVICE: 120, // rolling telemetry history points
  DISCOVERY_CONCURRENCY: 30,
};

export const INITIAL_DEVICES = [
  {
    id: "dev-core-router-01",
    name: "CCR2004-Core-Router",
    ip: "192.168.1.1",
    mac: "48:8F:5A:11:22:33",
    vendor: "MikroTik",
    type: "router",
    brand: "mikrotik",
    protocol: "routeros",
    location: "Main Server Room - Rack A1",
    zone: "core",
    upstream_id: null,
    tags: ["gateway", "wan-failover", "bgp", "dhcp-server"],
    enabled: true,
    pollInterval: 15,
    created_at: Date.now() - 86400000 * 30,
    updated_at: Date.now(),
  },
  {
    id: "dev-dist-switch-01",
    name: "Cisco-Core-Distribution-SW",
    ip: "192.168.1.2",
    mac: "00:26:0B:44:55:66",
    vendor: "Cisco Systems",
    type: "switch",
    brand: "cisco",
    protocol: "snmp",
    location: "Main Server Room - Rack A2",
    zone: "distribution",
    upstream_id: "dev-core-router-01",
    tags: ["10g-fiber-aggregator", "vlan-trunk"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 30,
    updated_at: Date.now(),
  },
  {
    id: "dev-sw1-poe",
    name: "SW-Site-01-PoE-24P",
    ip: "192.168.1.10",
    mac: "74:83:C2:10:20:30",
    vendor: "Ubiquiti Networks",
    type: "switch",
    brand: "ubiquiti",
    protocol: "snmp",
    location: "Site 1 - Network Rack",
    zone: "access",
    upstream_id: "dev-dist-switch-01",
    tags: ["poe-plus", "site-1"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-ap1-lr",
    name: "AP-Site1-MainLobby",
    ip: "192.168.1.11",
    mac: "74:83:C2:10:20:31",
    vendor: "Ubiquiti Networks",
    type: "ap",
    brand: "ubiquiti",
    protocol: "icmp",
    location: "Site 1 - Main Lobby Ceiling",
    zone: "access",
    upstream_id: "dev-sw1-poe",
    tags: ["wifi6", "guest-vlan", "site-1"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-ap1-master",
    name: "AP-Site1-ExecutiveSuite",
    ip: "192.168.1.12",
    mac: "74:83:C2:10:20:32",
    vendor: "Ubiquiti Networks",
    type: "ap",
    brand: "ubiquiti",
    protocol: "icmp",
    location: "Site 1 - Executive Suite",
    zone: "access",
    upstream_id: "dev-sw1-poe",
    tags: ["wifi6", "site-1"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-cam1-entrance",
    name: "CAM-Site1-MainGate",
    ip: "192.168.1.15",
    mac: "BC:AD:28:44:88:99",
    vendor: "Hikvision",
    type: "camera",
    brand: "hikvision",
    protocol: "icmp",
    location: "Site 1 - Front Gate",
    zone: "cctv",
    upstream_id: "dev-sw1-poe",
    tags: ["4k-ir", "nvr-stream1", "cctv"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 15,
    updated_at: Date.now(),
  },
  {
    id: "dev-sw2-poe",
    name: "SW-Site-02-PoE-24P",
    ip: "192.168.1.20",
    mac: "74:83:C2:20:30:40",
    vendor: "Ubiquiti Networks",
    type: "switch",
    brand: "ubiquiti",
    protocol: "snmp",
    location: "Site 2 - Utility Room",
    zone: "access",
    upstream_id: "dev-dist-switch-01",
    tags: ["poe-plus", "site-2"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-ap2-suite",
    name: "AP-Site2-MainLounge",
    ip: "192.168.1.21",
    mac: "74:83:C2:20:30:41",
    vendor: "Ubiquiti Networks",
    type: "ap",
    brand: "ubiquiti",
    protocol: "icmp",
    location: "Site 2 - Lounge Area",
    zone: "access",
    upstream_id: "dev-sw2-poe",
    tags: ["wifi6", "site-2"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-cam2-pool",
    name: "CAM-Site2-Perimeter",
    ip: "192.168.1.25",
    mac: "BC:AD:28:99:11:22",
    vendor: "Hikvision",
    type: "camera",
    brand: "hikvision",
    protocol: "icmp",
    location: "Site 2 - Perimeter Deck",
    zone: "cctv",
    upstream_id: "dev-sw2-poe",
    tags: ["ptz-cctv", "site-2"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 15,
    updated_at: Date.now(),
  },
  {
    id: "dev-sw-clubhouse",
    name: "SW-Clubhouse-PoE",
    ip: "192.168.1.30",
    mac: "00:1E:BD:55:66:77",
    vendor: "TP-Link",
    type: "switch",
    brand: "tplink",
    protocol: "snmp",
    location: "Clubhouse & Restaurant - Office",
    zone: "access",
    upstream_id: "dev-dist-switch-01",
    tags: ["poe", "clubhouse", "pos-network"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 20,
    updated_at: Date.now(),
  },
  {
    id: "dev-nas-cctv-nvr",
    name: "Synology-CCTV-NVR-NAS",
    ip: "192.168.1.50",
    mac: "00:11:32:88:99:AA",
    vendor: "Synology",
    type: "nas",
    brand: "synology",
    protocol: "snmp",
    location: "Main Server Room - Rack B1",
    zone: "core",
    upstream_id: "dev-dist-switch-01",
    tags: ["raid6-storage", "surveillance-station", "backup"],
    enabled: true,
    pollInterval: 30,
    created_at: Date.now() - 86400000 * 25,
    updated_at: Date.now(),
  },
  {
    id: "dev-solar-iot-gateway",
    name: "Solar-Inverter-Modbus-Gateway",
    ip: "192.168.1.90",
    mac: "24:62:AB:33:44:55",
    vendor: "Espressif Systems",
    type: "gateway",
    brand: "generic",
    protocol: "icmp",
    location: " Utilities - Power Room",
    zone: "iot",
    upstream_id: "dev-dist-switch-01",
    tags: ["solar-energy", "telemetry", "modbus-tcp"],
    enabled: true,
    pollInterval: 60,
    created_at: Date.now() - 86400000 * 10,
    updated_at: Date.now(),
  },
];
